version = 1

[[annotations]]
path = [
  "README.md",
  "CODE_OF_CONDUCT.md",
  # Debian files (some excluded from linting)
  "debian/changelog",
  "debian/control",
  "debian/extras/**",
  "debian/notolog.1",
  "debian/notolog.lintian-overrides",
  "debian/README.md",
  "debian/source/format",
  # PyInstaller build metadata
  "pyinstaller/dependencies/*",
  "pyinstaller/scripts/README.md",
  # Application source files
  "src/**",
]
SPDX-FileCopyrightText = "2025 Vadim Bakhrenkov"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "src/notolog/assets/fonts/IBMPlexMono/*",
]
SPDX-FileCopyrightText = '© 2017 IBM Corp. with Reserved Font Name "Plex"'
SPDX-License-Identifier = 'OFL-1.1'

[[annotations]]
path = [
  "src/notolog/assets/fonts/NotoSans/*",
]
SPDX-FileCopyrightText = "2022 The Noto Project Authors (https://github.com/notofonts/latin-greek-cyrillic)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "src/notolog/assets/themes/default/icons/*",
]
SPDX-FileCopyrightText = "(c) 2019-2024 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"
